# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99c0c7b27a61232303e58a7402aff0e10c3842b01208bc09a8d9f9edde83a54da78d79ecfa51b049b4b432c0d59912142cc3978a3ae53a4052bb45690848f232

test:
  secret_key_base: 1aa58ba39ca176f86e217900fcb13a686a64957f171fabd6a57129f1f578c689a96e8843980063f190269ae051921108d39669c903e5589551bc89040abb51cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
